dist: bionic
sudo: required

language: c

os:
  - linux

compiler:
  - gcc

addons:
  apt:
    packages:
      - cmake
      - valgrind
      - cppcheck
      - lcov
      - gcovr

before_script:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
  - sudo apt update
  - sudo apt install gcc-snapshot
  - sudo apt install gcc-6 g++-6
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6
  - sudo apt-get install -y libgtest-dev
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt && sudo make
  - sudo cp *.a /usr/lib
  - cd "${TRAVIS_BUILD_DIR}"
  - cd HW_2
  - cd tests
  - bash generate_tests.sh
  - cd ..
  - cmake .
  - make

script:
  - ./TEST
  - valgrind --track-origins=yes --leak-check=full ./TEST_VALGRIND
  - cppcheck --enable=warning,performance,portability,style --language=c++ ./project
  - cd "${TRAVIS_BUILD_DIR}"
#  - gcovr -r ..
  - bash <(curl -s https://codecov.io/bash)