dist: bionic
sudo: required

language: c

os:
  - osx

compiler:
  - clang

addons:
  homebrew:
    packages:
      - cmake

before_script:
  - git clone git://sourceware.org/git/valgrind.git
    - cd valgrind
    - ./autogen.sh
    - ./configure
    - make
    - sudo make install
    - brew install cppcheck
    - git clone https://github.com/google/googletest
    - cd googletest
    - mkdir build
    - cd build
    - cmake ..
    - make
    - make install
    - cd "${TRAVIS_BUILD_DIR}"
    - cd HW_2
    - cd tests
    - bash generate_tests.sh
    - cd ..
    - cmake .
    - make

script:
  - ./TEST
  - valgrind --track-origins=yes --leak-check=full ./TEST_VALGRIND
  - cppcheck --enable=warning,performance,portability,style --language=c++ ./project
  - cd "${TRAVIS_BUILD_DIR}"
#  - gcovr -r ..
  - bash <(curl -s https://codecov.io/bash)