dist: xenial
sudo: required
os: linux


matrix:
  include:
    - os: linux
        addons:
          apt:
            sources:
              - llvm-toolchain-trusty-5.0
            packages:
              - clang-5.0
        env:
          - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

    before_install:
      - eval "${MATRIX_EVAL}"

language: c





compiler:
  - gcc

addons:
  apt:
    packages:
      - cmake
      - valgrind
      - cppcheck
      - lcov
      - gcovr

before_script:
  - sudo apt-get install -y libgtest-dev
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt && sudo make
  - sudo cp *.a /usr/lib
  - cd "${TRAVIS_BUILD_DIR}"
  - cd HW_2
  - cd tests
  - bash generate_tests.sh
  - cd ..
  - cmake .
  - make

script:
  - ./TEST
  - valgrind --track-origins=yes --leak-check=full ./TEST_VALGRIND
  - cppcheck --enable=warning,performance,portability,style --language=c++ ./project
  - cd "${TRAVIS_BUILD_DIR}"
#  - gcovr -r ..
  - bash <(curl -s https://codecov.io/bash)